/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedForbiddenRouteImport } from './routes/_protected/forbidden'
import { Route as ProtectedUserManagementRouteRouteImport } from './routes/_protected/user-management/route'
import { Route as AuthSigninIndexRouteImport } from './routes/_auth/signin/index'
import { Route as ProtectedChannelPartnersIndexRouteImport } from './routes/_protected/channel-partners/index'
import { Route as ProtectedLeadsIndexRouteImport } from './routes/_protected/leads/index'
import { Route as ProtectedMeetingsIndexRouteImport } from './routes/_protected/meetings/index'
import { Route as ProtectedProjectsIndexRouteImport } from './routes/_protected/projects/index'
import { Route as ProtectedUserManagementRolesIndexRouteImport } from './routes/_protected/user-management/roles/index'
import { Route as ProtectedUserManagementUsersIndexRouteImport } from './routes/_protected/user-management/users/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedForbiddenRoute = ProtectedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUserManagementRouteRoute =
  ProtectedUserManagementRouteRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedChannelPartnersIndexRoute =
  ProtectedChannelPartnersIndexRouteImport.update({
    id: '/channel-partners/',
    path: '/channel-partners/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLeadsIndexRoute = ProtectedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMeetingsIndexRoute = ProtectedMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProjectsIndexRoute = ProtectedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUserManagementRolesIndexRoute =
  ProtectedUserManagementRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => ProtectedUserManagementRouteRoute,
  } as any)
const ProtectedUserManagementUsersIndexRoute =
  ProtectedUserManagementUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ProtectedUserManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user-management': typeof ProtectedUserManagementRouteRouteWithChildren
  '/forbidden': typeof ProtectedForbiddenRoute
  '/signin/': typeof AuthSigninIndexRoute
  '/channel-partners/': typeof ProtectedChannelPartnersIndexRoute
  '/leads/': typeof ProtectedLeadsIndexRoute
  '/meetings/': typeof ProtectedMeetingsIndexRoute
  '/projects/': typeof ProtectedProjectsIndexRoute
  '/user-management/roles/': typeof ProtectedUserManagementRolesIndexRoute
  '/user-management/users/': typeof ProtectedUserManagementUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user-management': typeof ProtectedUserManagementRouteRouteWithChildren
  '/forbidden': typeof ProtectedForbiddenRoute
  '/signin': typeof AuthSigninIndexRoute
  '/channel-partners': typeof ProtectedChannelPartnersIndexRoute
  '/leads': typeof ProtectedLeadsIndexRoute
  '/meetings': typeof ProtectedMeetingsIndexRoute
  '/projects': typeof ProtectedProjectsIndexRoute
  '/user-management/roles': typeof ProtectedUserManagementRolesIndexRoute
  '/user-management/users': typeof ProtectedUserManagementUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/user-management': typeof ProtectedUserManagementRouteRouteWithChildren
  '/_protected/forbidden': typeof ProtectedForbiddenRoute
  '/_auth/signin/': typeof AuthSigninIndexRoute
  '/_protected/channel-partners/': typeof ProtectedChannelPartnersIndexRoute
  '/_protected/leads/': typeof ProtectedLeadsIndexRoute
  '/_protected/meetings/': typeof ProtectedMeetingsIndexRoute
  '/_protected/projects/': typeof ProtectedProjectsIndexRoute
  '/_protected/user-management/roles/': typeof ProtectedUserManagementRolesIndexRoute
  '/_protected/user-management/users/': typeof ProtectedUserManagementUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user-management'
    | '/forbidden'
    | '/signin/'
    | '/channel-partners/'
    | '/leads/'
    | '/meetings/'
    | '/projects/'
    | '/user-management/roles/'
    | '/user-management/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user-management'
    | '/forbidden'
    | '/signin'
    | '/channel-partners'
    | '/leads'
    | '/meetings'
    | '/projects'
    | '/user-management/roles'
    | '/user-management/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_protected/user-management'
    | '/_protected/forbidden'
    | '/_auth/signin/'
    | '/_protected/channel-partners/'
    | '/_protected/leads/'
    | '/_protected/meetings/'
    | '/_protected/projects/'
    | '/_protected/user-management/roles/'
    | '/_protected/user-management/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/forbidden': {
      id: '/_protected/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ProtectedForbiddenRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/user-management': {
      id: '/_protected/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof ProtectedUserManagementRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/signin/': {
      id: '/_auth/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/channel-partners/': {
      id: '/_protected/channel-partners/'
      path: '/channel-partners'
      fullPath: '/channel-partners/'
      preLoaderRoute: typeof ProtectedChannelPartnersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leads/': {
      id: '/_protected/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof ProtectedLeadsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/meetings/': {
      id: '/_protected/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof ProtectedMeetingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/projects/': {
      id: '/_protected/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProtectedProjectsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/user-management/roles/': {
      id: '/_protected/user-management/roles/'
      path: '/roles'
      fullPath: '/user-management/roles/'
      preLoaderRoute: typeof ProtectedUserManagementRolesIndexRouteImport
      parentRoute: typeof ProtectedUserManagementRouteRoute
    }
    '/_protected/user-management/users/': {
      id: '/_protected/user-management/users/'
      path: '/users'
      fullPath: '/user-management/users/'
      preLoaderRoute: typeof ProtectedUserManagementUsersIndexRouteImport
      parentRoute: typeof ProtectedUserManagementRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninIndexRoute: AuthSigninIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedUserManagementRouteRouteChildren {
  ProtectedUserManagementRolesIndexRoute: typeof ProtectedUserManagementRolesIndexRoute
  ProtectedUserManagementUsersIndexRoute: typeof ProtectedUserManagementUsersIndexRoute
}

const ProtectedUserManagementRouteRouteChildren: ProtectedUserManagementRouteRouteChildren =
  {
    ProtectedUserManagementRolesIndexRoute:
      ProtectedUserManagementRolesIndexRoute,
    ProtectedUserManagementUsersIndexRoute:
      ProtectedUserManagementUsersIndexRoute,
  }

const ProtectedUserManagementRouteRouteWithChildren =
  ProtectedUserManagementRouteRoute._addFileChildren(
    ProtectedUserManagementRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedUserManagementRouteRoute: typeof ProtectedUserManagementRouteRouteWithChildren
  ProtectedForbiddenRoute: typeof ProtectedForbiddenRoute
  ProtectedChannelPartnersIndexRoute: typeof ProtectedChannelPartnersIndexRoute
  ProtectedLeadsIndexRoute: typeof ProtectedLeadsIndexRoute
  ProtectedMeetingsIndexRoute: typeof ProtectedMeetingsIndexRoute
  ProtectedProjectsIndexRoute: typeof ProtectedProjectsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedUserManagementRouteRoute:
    ProtectedUserManagementRouteRouteWithChildren,
  ProtectedForbiddenRoute: ProtectedForbiddenRoute,
  ProtectedChannelPartnersIndexRoute: ProtectedChannelPartnersIndexRoute,
  ProtectedLeadsIndexRoute: ProtectedLeadsIndexRoute,
  ProtectedMeetingsIndexRoute: ProtectedMeetingsIndexRoute,
  ProtectedProjectsIndexRoute: ProtectedProjectsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
