/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthSigninIndexRouteImport } from './routes/_auth/signin/index'
import { Route as ProtectedChannelPartnersIndexRouteImport } from './routes/_protected/channel-partners/index'
import { Route as ProtectedLeadsIndexRouteImport } from './routes/_protected/leads/index'
import { Route as ProtectedProjectsIndexRouteImport } from './routes/_protected/projects/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedChannelPartnersIndexRoute =
  ProtectedChannelPartnersIndexRouteImport.update({
    id: '/channel-partners/',
    path: '/channel-partners/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLeadsIndexRoute = ProtectedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProjectsIndexRoute = ProtectedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin/': typeof AuthSigninIndexRoute
  '/channel-partners/': typeof ProtectedChannelPartnersIndexRoute
  '/leads/': typeof ProtectedLeadsIndexRoute
  '/projects/': typeof ProtectedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof AuthSigninIndexRoute
  '/channel-partners': typeof ProtectedChannelPartnersIndexRoute
  '/leads': typeof ProtectedLeadsIndexRoute
  '/projects': typeof ProtectedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/signin/': typeof AuthSigninIndexRoute
  '/_protected/channel-partners/': typeof ProtectedChannelPartnersIndexRoute
  '/_protected/leads/': typeof ProtectedLeadsIndexRoute
  '/_protected/projects/': typeof ProtectedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin/' | '/channel-partners/' | '/leads/' | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/channel-partners' | '/leads' | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/signin/'
    | '/_protected/channel-partners/'
    | '/_protected/leads/'
    | '/_protected/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signin/': {
      id: '/_auth/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/channel-partners/': {
      id: '/_protected/channel-partners/'
      path: '/channel-partners'
      fullPath: '/channel-partners/'
      preLoaderRoute: typeof ProtectedChannelPartnersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leads/': {
      id: '/_protected/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof ProtectedLeadsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/projects/': {
      id: '/_protected/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProtectedProjectsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninIndexRoute: AuthSigninIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedChannelPartnersIndexRoute: typeof ProtectedChannelPartnersIndexRoute
  ProtectedLeadsIndexRoute: typeof ProtectedLeadsIndexRoute
  ProtectedProjectsIndexRoute: typeof ProtectedProjectsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedChannelPartnersIndexRoute: ProtectedChannelPartnersIndexRoute,
  ProtectedLeadsIndexRoute: ProtectedLeadsIndexRoute,
  ProtectedProjectsIndexRoute: ProtectedProjectsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
